# configure with version "2"
Vagrant.configure("2") do |config|
  box = "ubuntu/xenial64"

  config.vm.box = box
  config.vm.box_check_update = true
  config.vm.provider "virtualbox" do |v|
    v.cpus = 1
    v.memory = 1024
  end

  config.vm.synced_folder "../packages/", "/vagrant/packages"
  config.vm.synced_folder "../scripts/", "/vagrant/scripts"

  # avoid 'Innapropriate ioctl for device' messages
  # see vagrant config doc for more info: https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # create master node
  config.vm.define "jenkins-master" do |n|
    n.vm.box = box

    n.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
    n.vm.network "private_network", ip: "192.168.50.2"

    n.vm.provision "install-java", type: "shell", path: "../scripts/install-java"
    n.vm.provision "install-jenkins", type: "shell", path: "../scripts/install-jenkins"
  end

  # spin up identical slaves
  (0..1).each do |i|
    config.vm.define "slave-#{i}" do |s|
      s.vm.box = box

      s.vm.network "private_network", ip: "192.168.50.#{i + 3}"

      # give slaves more horsepower
      s.vm.provider "virtualbox" do |v|
        v.cpus = 2
        v.memory = 2048
      end

      s.vm.provision "create-user", type: "shell",
        inline: "sudo /vagrant/scripts/create-user jenkins-slave"
      s.vm.provision "create-key", type: "shell",
        inline: "sudo -u jenkins-slave ssh-keygen -f /home/jenkins-slave/.ssh/id_rsa -N ''"
    end
  end
end
