# define dedicated ips for the jenkins machines
machine_ips = {
 "jenkins_master" => "192.168.50.2",
 "jenkins_slave_0" =>"192.168.50.3",
 "jenkins_slave_1" => "192.168.50.4",
}

# configure with version "2"
Vagrant.configure("2") do |config|
  box = "ubuntu/xenial64"

  config.vm.box = box
  config.vm.box_check_update = true
  config.vm.provider "virtualbox" do |v|
    v.cpus = 1
    v.memory = 1024
  end

  config.vm.synced_folder "../packages/", "/vagrant/packages"
  config.vm.synced_folder "../scripts/", "/vagrant/scripts"

  # avoid 'Innapropriate ioctl for device' messages
  # see vagrant config doc for more info: https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # create master node
  config.vm.define "jenkins_master" do |n|
    n.vm.box = box

    n.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
    n.vm.network "private_network", ip: machine_ips['jenkins_master']

    n.vm.provision "install-java", type: "shell", path: "../scripts/install-java"
    n.vm.provision "install-jenkins", type: "shell", path: "../scripts/install-jenkins"
  end

  # spin up identical slaves
  (0..1).each do |i|
    machine_name = "jenkins_slave_#{i}"

    config.vm.define machine_name do |s|
      s.vm.box = box
      s.vm.network "private_network", ip: machine_ips[machine_name]

      # give slaves more horsepower
      s.vm.provider "virtualbox" do |v|
        v.cpus = 2
        v.memory = 2048
      end

      user = 'jenkins-slave'

      s.vm.provision "create-user", type: "shell",
        inline: "sudo /vagrant/scripts/create-user #{user}"

      s.vm.provision "create-key", type: "shell",
        inline: "sudo -u #{user} ssh-keygen -f /home/#{user}/.ssh/id_rsa -N ''"
    end
  end
end
