workers = 2
master_port = 6443
master_ip = '192.168.50.2'
ip_offset = 2

# configure with version "2"
Vagrant.configure("2") do |config|
  box = "ubuntu/bionic64"

  config.vm.box = box
  config.vm.box_check_update = true

  config.vm.synced_folder "../packages/", "/vagrant/packages"
  config.vm.synced_folder "../scripts/", "/vagrant/scripts"

  # avoid 'Innapropriate ioctl for device' messages
  # see vagrant config doc for more info: https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # set up master node
  config.vm.define "kubernetes-master" do |km|
    km.vm.box = box
    km.vm.provider "virtualbox" do |v|
      v.cpus = 2
      v.memory = 2048
    end

    km.vm.network "forwarded_port", guest: master_port, host: master_port, auto_correct: true
    km.vm.network "private_network", ip: master_ip

    km.vm.provision "bootstrap", type: "shell" do |s|
      s.inline = "apt-get update"
      # --no-install-recommends
    end

    km.vm.provision "disable-swapp", type: "shell", inline: "swapoff -a"
  end

  # set up worker nodes
  (1..workers).each do |i|
    config.vm.define "kubernetes-worker-#{i}" do |kw|
      kw.vm.box = box
      kw.vm.provider "virtualbox" do |v|
        v.cpus = 2
        v.memory = 2048
      end

      kw.vm.network "private_network", ip: "192.168.50.#{i + ip_offset}"

      kw.vm.provision "bootstrap", type: "shell" do |s|
        s.inline = "apt-get update"
      end

      kw.vm.provision "disable-swapp", type: "shell", inline: "swapoff -a"
    end
  end
end
