#!/usr/bin/env bash

# Reference for below commands: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl

apt-get update
apt-get install --no-install-recommends -y \
  apt-transport-https \
  curl

curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

cat <<EOF | tee /etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF

apt-get update
apt-get install --no-install-recommends -y \
  kubelet \
  kubeadm \
  kubectl
apt-mark hold kubelet kubeadm kubectl
