#!/usr/bin/env bash

# Reference for below: https://docs.docker.com/install/linux/docker-ce/ubuntu/

# install pre-reqs for docker
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
  apt-transport-https \
  ca-certificates \
  curl \
  gnupg-agent \
  software-properties-common

# add docker's gpg key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

# set up stable repository
add-apt-repository \
  "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

# install docker
apt-get update
apt-get install --no-install-recommends -y \
  docker-ce \
  docker-ce-cli \
  containerd.io

# Consider setting up a daemon to use systemd...kubeadm will warn that systemd is not being used
# Reference: https://kubernetes.io/docs/setup/production-environment/container-runtimes/
# Setup daemon
# cat > /etc/docker/daemon.json <<EOF
# {
#   "exec-opts": ["native.cgroupdriver=systemd"],
#   "log-driver": "json-file",
#   "log-opts": {
#     "max-size": "100m"
#   },
#   "storage-driver": "overlay2"
# }
# EOF
#
# mkdir -p /etc/systemd/system/docker.service.d
#
# # Restart docker.
# systemctl daemon-reload
# systemctl restart docker
