#!/usr/bin/env bash

# Reference for below: https://docs.docker.com/install/linux/docker-ce/ubuntu/

# install pre-reqs for docker
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
  apt-transport-https \
  ca-certificates \
  curl \
  gnupg-agent \
  software-properties-common

# add docker's gpg key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

# set up stable repository
add-apt-repository \
  "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

# install docker
apt-get update
apt-get install --no-install-recommends -y \
  docker-ce \
  docker-ce-cli \
  containerd.io
