#!/usr/bin/env bash

apt-get update
apt-get install -y --no-install-recommends python3 python3-pip pyton3-dev python3-venv python3.7

ln -s /usr/bin/python3 /usr/bin/python
ln -s /usr/bin/pip3 /usr/bin/pip
